#Requires -Version 5.1
#Requires -Modules VirtualMachineManager
<#
.SYNOPSIS
    Batch ESXi-to-HyperV VM migration via SCVMM V2V conversion.
.DESCRIPTION
    Reads a CSV of VM migration specs and performs V2V conversion through SCVMM,
    then enables Guest Services and configures high availability for each VM.

    Supports up to 4 NICs per VM. Empty NIC columns in the CSV are skipped.

    The CSV is designed to be generated by Export-MigrationCsv.ps1, which pulls
    VM data from VMware via PowerCLI. SCVMM object IDs are resolved at runtime
    by name — not hardcoded in the CSV.

    MODULE CONFLICT NOTE:
    PowerCLI and Hyper-V modules share cmdlet names (e.g., Get-VM). This script
    uses module-qualified calls (Hyper-V\Get-VM) to avoid ambiguity. SCVMM cmdlets
    (*-SC*) do not conflict and are called unqualified.
.PARAMETER CsvPath
    Path to the migration CSV file.
.PARAMETER VMMServer
    FQDN of the SCVMM management server.
.PARAMETER WhatIf
    Runs pre-flight validation and CSV parsing without executing conversions.
.EXAMPLE
    .\Convert-EsxiToHyperV.ps1 -CsvPath .\configs\migration-export.csv -VMMServer medwvmmp001v.gwnsm.guidewell.net
.EXAMPLE
    .\Convert-EsxiToHyperV.ps1 -CsvPath .\configs\migration-export.csv -VMMServer medwvmmp001v.gwnsm.guidewell.net -WhatIf
#>
[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$CsvPath,

    [Parameter(Mandatory)]
    [string]$VMMServer
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Resolve Full Paths ────────────────────────────────────────────────────────
$scriptDir  = Split-Path -Parent (Resolve-Path $MyInvocation.MyCommand.Path)
$modulePath = Join-Path $scriptDir 'modules'

# Resolve CsvPath to absolute if relative was provided
if (-not [System.IO.Path]::IsPathRooted($CsvPath)) {
    $CsvPath = Join-Path (Get-Location).Path $CsvPath
}
$CsvPath = Resolve-Path $CsvPath

# ── Load Modules ──────────────────────────────────────────────────────────────
Import-Module (Join-Path $modulePath 'MigrationLogger.psm1')    -Force
Import-Module (Join-Path $modulePath 'PreFlightValidator.psm1')  -Force
Import-Module (Join-Path $modulePath 'MigrationEngine.psm1')     -Force
Import-Module (Join-Path $modulePath 'PostConversionConfig.psm1') -Force

# ── Helper: Parse NIC Columns from CSV Row ────────────────────────────────────
function Get-NICsFromRow {
    <#
    .SYNOPSIS
        Extracts NIC configurations from a CSV row. Supports NIC1 through NIC4.
        Uses VMware source fields (SourcePortGroup) and SCVMM target fields
        (TargetSwitch, TargetVMNetwork).
    #>
    param([PSObject]$Row)

    $nics = @()
    foreach ($i in 1..4) {
        $targetSwitch = $Row."NIC${i}_TargetSwitch"
        if ([string]::IsNullOrWhiteSpace($targetSwitch)) { continue }

        $nics += @{
            SourcePortGroup = $Row."NIC${i}_SourcePortGroup"
            VLAN            = [int]$Row."NIC${i}_VLAN"
            TargetSwitch    = $targetSwitch
            TargetVMNetwork = $Row."NIC${i}_TargetVMNetwork"
        }
    }
    return $nics
}

# ── Helper: Validate CSV Columns ─────────────────────────────────────────────
function Test-CsvColumns {
    param([string[]]$Headers)

    $required = @(
        'VMName', 'SourceHost', 'TargetHost', 'StoragePath',
        'CPUCount', 'MemoryMB', 'Generation', 'DelayedStartSec',
        'NIC1_VLAN', 'NIC1_TargetSwitch', 'NIC1_TargetVMNetwork'
    )
    $missing = $required | Where-Object { $_ -notin $Headers }
    if ($missing) {
        throw "CSV is missing required columns: $($missing -join ', ')"
    }
}

# ══════════════════════════════════════════════════════════════════════════════
#  MAIN EXECUTION
# ══════════════════════════════════════════════════════════════════════════════

$logDir = Join-Path $scriptDir 'logs'
Start-MigrationLog -LogDirectory $logDir

$results = [System.Collections.ArrayList]::new()

try {
    # ── Import and Validate CSV ───────────────────────────────────────────────
    Write-MigrationLog -Message "Importing CSV: $CsvPath" -Level Info
    $csvData = Import-Csv -Path $CsvPath
    if ($csvData.Count -eq 0) { throw "CSV file is empty." }

    $headers = ($csvData | Get-Member -MemberType NoteProperty).Name
    Test-CsvColumns -Headers $headers

    Write-MigrationLog -Message "Found $($csvData.Count) VM(s) in CSV." -Level Info

    # ── Shared Pre-Flight ─────────────────────────────────────────────────────
    Write-MigrationLog -Message "Running shared pre-flight checks..." -Level Info

    $moduleCheck = Test-RequiredModules
    if (-not $moduleCheck.Success) {
        throw "Pre-flight failed: $($moduleCheck.ErrorMessage)"
    }
    Write-MigrationLog -Message "Required modules verified." -Level Success

    $vmmCheck = Test-VMMServerConnection -VMMServer $VMMServer
    if (-not $vmmCheck.Success) {
        throw "Pre-flight failed: $($vmmCheck.ErrorMessage)"
    }
    Write-MigrationLog -Message "VMM server connection verified." -Level Success

    # ── Process Each VM ───────────────────────────────────────────────────────
    foreach ($row in $csvData) {
        $vmName  = $row.VMName
        $vmTimer = [System.Diagnostics.Stopwatch]::StartNew()

        Write-MigrationLog -Message "Starting migration..." -Level Info -VMName $vmName

        try {
            $nics = Get-NICsFromRow -Row $row
            if ($nics.Count -eq 0) {
                throw "No NIC configurations found in CSV row."
            }

            # ── VM-Specific Pre-Flight ────────────────────────────────────────
            Write-MigrationLog -Message "Validating target host '$($row.TargetHost)'..." -Level Info -VMName $vmName
            $hostCheck = Test-TargetHost -VMMServer $VMMServer -TargetHost $row.TargetHost
            if (-not $hostCheck.Success) { throw $hostCheck.ErrorMessage }
            Write-MigrationLog -Message "Target host OK." -Level Success -VMName $vmName

            Write-MigrationLog -Message "Validating source VM on '$($row.SourceHost)'..." -Level Info -VMName $vmName
            $vmCheck = Test-SourceVM -VMMServer $VMMServer `
                                     -VMName $vmName `
                                     -SourceHost $row.SourceHost
            if (-not $vmCheck.Success) { throw $vmCheck.ErrorMessage }
            Write-MigrationLog -Message "Source VM verified." -Level Success -VMName $vmName

            Write-MigrationLog -Message "Validating target resources (storage, switches, networks)..." -Level Info -VMName $vmName
            $resCheck = Test-TargetResources -VMMServer $VMMServer `
                                             -TargetHost $row.TargetHost `
                                             -TargetHostID $hostCheck.Data.ID `
                                             -StoragePath $row.StoragePath `
                                             -NICs $nics
            if (-not $resCheck.Success) { throw $resCheck.ErrorMessage }
            Write-MigrationLog -Message "Target resources verified." -Level Success -VMName $vmName

            # ── V2V Conversion ────────────────────────────────────────────────
            Write-MigrationLog -Message "Starting V2V conversion..." -Level Info -VMName $vmName
            $convResult = Invoke-V2VConversion -VMMServer $VMMServer `
                                               -VMName $vmName `
                                               -SourceHost $row.SourceHost `
                                               -TargetHost $row.TargetHost `
                                               -StoragePath $row.StoragePath `
                                               -CPUCount ([int]$row.CPUCount) `
                                               -MemoryMB ([int]$row.MemoryMB) `
                                               -Generation ([int]$row.Generation) `
                                               -DelayedStartSec ([int]$row.DelayedStartSec) `
                                               -NICs $nics

            if ($convResult -and -not $convResult.Success) {
                throw "V2V conversion failed: $($convResult.ErrorMessage)"
            }
            Write-MigrationLog -Message "V2V conversion completed." -Level Success -VMName $vmName

            # ── Post-Conversion: Guest Services ───────────────────────────────
            Write-MigrationLog -Message "Enabling Guest Services..." -Level Info -VMName $vmName
            $gsResult = Enable-GuestServices -VMName $vmName -ComputerName $row.TargetHost
            if (-not $gsResult.Success) { throw $gsResult.ErrorMessage }
            Write-MigrationLog -Message "Guest Services enabled." -Level Success -VMName $vmName

            # ── Post-Conversion: High Availability ────────────────────────────
            Write-MigrationLog -Message "Configuring high availability..." -Level Info -VMName $vmName
            $haResult = Add-HighAvailability -VMName $vmName -ComputerName $row.TargetHost
            if (-not $haResult.Success) { throw $haResult.ErrorMessage }
            Write-MigrationLog -Message "High availability configured." -Level Success -VMName $vmName

            # ── Post-Conversion Verification ──────────────────────────────────
            Write-MigrationLog -Message "Running post-conversion verification..." -Level Info -VMName $vmName
            $verifyResult = Test-PostConversion -VMName $vmName `
                                                -ComputerName $row.TargetHost `
                                                -VMMServer $VMMServer `
                                                -ExpectedNICs $nics
            if (-not $verifyResult.Success) {
                Write-MigrationLog -Message "Post-conversion warnings: $($verifyResult.ErrorMessage)" -Level Warning -VMName $vmName
            }
            else {
                Write-MigrationLog -Message "Post-conversion verification passed." -Level Success -VMName $vmName
            }

            $vmTimer.Stop()
            $results.Add((New-MigrationResult -VMName $vmName -Status 'Success' -Phase 'Complete' -Duration $vmTimer.Elapsed)) | Out-Null
            Write-MigrationLog -Message "Migration completed successfully in $($vmTimer.Elapsed.ToString('hh\:mm\:ss'))." -Level Success -VMName $vmName
        }
        catch {
            $vmTimer.Stop()
            $failPhase = switch -Wildcard ($_.Exception.Message) {
                '*Target host*'     { 'PreFlight-TargetHost' }
                '*Source VM*'       { 'PreFlight-SourceVM' }
                '*Target resources*' { 'PreFlight-Resources' }
                '*V2V conversion*'  { 'V2V-Conversion' }
                '*Guest Services*'  { 'PostConversion-GuestServices' }
                '*highly available*' { 'PostConversion-HA' }
                default             { 'Unknown' }
            }
            $results.Add((New-MigrationResult -VMName $vmName -Status 'Failed' -Phase $failPhase -ErrorMessage $_.Exception.Message -Duration $vmTimer.Elapsed)) | Out-Null
            Write-MigrationLog -Message "FAILED at phase '$failPhase': $($_.Exception.Message)" -Level Error -VMName $vmName
        }
    }

    # ── Summary ───────────────────────────────────────────────────────────────
    Write-MigrationSummary -Results $results
}
catch {
    Write-MigrationLog -Message "FATAL: $($_.Exception.Message)" -Level Error
    throw
}
finally {
    Stop-MigrationLog -ExportCsv
}
